### ISSUE TITLE
Gitter deletes branch name prefix when checking out

### ISSUE THREAD

**Issue by quibbleahr** [elifiner/gitter#2]
When I have a branch I want to check out, after typing `gt checkout`, I select the branch I want to checkout, say, `feature/branch_name`.
I actually get switched to branch `branch_name`, ignoring the `feature` part. Then, when I commit and push my changes to the head, it will create a new branch `branch_name` instead of updating `feature/branch_name`.

**Comment by finereli** [comment]
Your ticket is a testament to how few people use `gitter`. When I wrote it I worked at a company that used the `username/branch` notation for branches and it made sense to drop the username part. It doesn't make sense for general use.

**Comment by finereli** [comment]
Fixed it :).
